if(NOT EXISTS "${MAP_FILE}")
  message(FATAL_ERROR "Keylink Combo listener order check: map file is missing: ${MAP_FILE}")
endif()

if(NOT EXISTS "${DT_HEADER_FILE}")
  message(FATAL_ERROR "Keylink Combo devicetree validation: generated header is missing: ${DT_HEADER_FILE}")
endif()

file(READ "${DT_HEADER_FILE}" dt_header)
string(REGEX MATCH "#define DT_N_S_combos_FOREACH_CHILD\\(fn\\)[^\n]*" combo_children_line "${dt_header}")
string(REGEX MATCHALL "fn\\((DT_N_S_combos_S_[A-Za-z0-9_]+)\\)" combo_child_matches "${combo_children_line}")

set(combo_nodes "")
foreach(child_match IN LISTS combo_child_matches)
  string(REGEX REPLACE "fn\\((DT_N_S_combos_S_[A-Za-z0-9_]+)\\)" "\\1" child_node "${child_match}")
  list(APPEND combo_nodes "${child_node}")
endforeach()

function(keylink_combo_dt_list node property result)
  string(REGEX MATCH "#define ${node}_P_${property} \\{[^}]*\\}" property_line "${dt_header}")
  if(NOT property_line)
    set(${result} "" PARENT_SCOPE)
    return()
  endif()
  string(REGEX REPLACE ".*\\{([^}]*)\\}.*" "\\1" values "${property_line}")
  string(REGEX REPLACE "/\\*[^*]*\\*/" "" values "${values}")
  string(REPLACE "," ";" values "${values}")
  set(clean_values "")
  foreach(value IN LISTS values)
    string(STRIP "${value}" value)
    if(NOT value STREQUAL "")
      list(APPEND clean_values "${value}")
    endif()
  endforeach()
  set(${result} "${clean_values}" PARENT_SCOPE)
endfunction()

function(keylink_combo_dt_key_set node result)
  keylink_combo_dt_list("${node}" "key_positions" keys)
  list(SORT keys COMPARE NATURAL ORDER ASCENDING)
  string(JOIN "," key_set ${keys})
  set(${result} "${key_set}" PARENT_SCOPE)
endfunction()

function(keylink_combo_dt_layer_mask node result)
  keylink_combo_dt_list("${node}" "layers" layers)
  if("${layers}" STREQUAL "")
    set(${result} 0 PARENT_SCOPE)
    return()
  endif()
  set(mask 0)
  foreach(layer IN LISTS layers)
    math(EXPR mask "${mask} | (1 << ${layer})")
  endforeach()
  set(${result} "${mask}" PARENT_SCOPE)
endfunction()

list(LENGTH combo_nodes combo_node_count)
if(combo_node_count GREATER 1)
  math(EXPR combo_last_index "${combo_node_count} - 1")
  foreach(left_index RANGE 0 ${combo_last_index})
    list(GET combo_nodes ${left_index} left_node)
    keylink_combo_dt_key_set("${left_node}" left_keys)
    keylink_combo_dt_layer_mask("${left_node}" left_layers)
    math(EXPR right_first "${left_index} + 1")
    if(right_first GREATER combo_last_index)
      continue()
    endif()
    foreach(right_index RANGE ${right_first} ${combo_last_index})
      list(GET combo_nodes ${right_index} right_node)
      keylink_combo_dt_key_set("${right_node}" right_keys)
      keylink_combo_dt_layer_mask("${right_node}" right_layers)
      if(left_keys STREQUAL right_keys)
        math(EXPR overlap "${left_layers} & ${right_layers}")
        if(left_layers EQUAL 0 OR right_layers EQUAL 0 OR NOT overlap EQUAL 0)
          message(FATAL_ERROR "Keylink Combo devicetree validation failed: duplicate key set {${left_keys}} overlaps between ${left_node} (layers=0x${left_layers}) and ${right_node} (layers=0x${right_layers})")
        endif()
      endif()
    endforeach()
  endforeach()
endif()

file(READ "${MAP_FILE}" map)

function(keylink_combo_subscription_index symbol output)
  string(FIND "${map}" "${symbol}" index)
  set(${output} "${index}" PARENT_SCOPE)
endfunction()

keylink_combo_subscription_index("zmk_event_sub_rawhid_app_combo_runtimezmk_position_state_changed" keylink)
keylink_combo_subscription_index("zmk_event_sub_activityzmk_position_state_changed" activity)
keylink_combo_subscription_index("zmk_event_sub_behavior_hold_tapzmk_position_state_changed" hold_tap)
keylink_combo_subscription_index("zmk_event_sub_keymapzmk_position_state_changed" keymap)
keylink_combo_subscription_index("zmk_listener_combo" stock_listener)
keylink_combo_subscription_index("zmk_event_sub_combozmk_position_state_changed" stock_subscription)

if(keylink LESS 0 OR activity LESS 0 OR keymap LESS 0)
  message(FATAL_ERROR "Keylink Combo listener order check: required subscription missing (Keylink=${keylink}, activity=${activity}, keymap=${keymap})")
endif()

# hold-tap is absent in keymaps that do not instantiate &mt/&lt. In builds where
# it exists it must be between activity and keymap.
if(NOT hold_tap LESS 0)
  set(detected "Keylink -> activity -> hold-tap -> keymap")
  if(NOT (keylink LESS activity AND activity LESS hold_tap AND hold_tap LESS keymap))
    message(FATAL_ERROR "Keylink Combo listener order check failed. Expected: Keylink -> activity -> hold-tap -> keymap. Detected map offsets: Keylink=${keylink}, activity=${activity}, hold-tap=${hold_tap}, keymap=${keymap}")
  endif()
else()
  set(detected "Keylink -> activity -> keymap (hold-tap absent)")
  if(NOT (keylink LESS activity AND activity LESS keymap))
    message(FATAL_ERROR "Keylink Combo listener order check failed. Expected: Keylink -> activity -> keymap. Detected map offsets: Keylink=${keylink}, activity=${activity}, keymap=${keymap}")
  endif()
endif()

if(NOT stock_listener LESS 0 OR NOT stock_subscription LESS 0)
  message(FATAL_ERROR "Keylink Combo listener order check failed: ZMK stock Combo listener/subscription is present")
endif()

message(STATUS "Keylink Combo listener order verified: ${detected}; stock Combo listener absent")
